name: Auto Create Branch, Draft PR, and Comment when Issue is Assigned and Labeled

on:
  issues:
    types: [assigned, labeled]

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 必要なラベルが存在するかチェック
      - name: Check for required labels
        run: |
          LABELS="${{ join(github.event.issue.labels.*.name, ' ') }}"
          if [[ ! "$LABELS" =~ "enhancement" ]] && [[ ! "$LABELS" =~ "bug" ]] && [[ ! "$LABELS" =~ "documentation" ]]; then
            echo "Required label not found. Exiting..."
            exit 78  # Exits the job but does not fail the workflow
          fi

      # issueのラベルとタイトルからプレフィックスとブランチ名を生成
      - name: Extract prefix and generate branch name
        run: |
          PREFIX=""
          LABELS=${{ join(github.event.issue.labels.*.name, ' ') }}
          for label in $LABELS; do
            if [[ "$label" == "enhancement" ]]; then
              PREFIX="feat"
              break
            elif [[ "$label" == "bug" ]]; then
              PREFIX="fix"
              break
            elif [[ "$label" == "documentation" ]]; then
              PREFIX="doc"
              break
            fi
          done
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | tr -s ' ' '-' | tr -cd '[:alnum:]-')
          BRANCH_NAME="${PREFIX:+$PREFIX_}issue-${{ github.event.issue.number }}_${ISSUE_TITLE}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch name generated: $BRANCH_NAME"

      # Gitユーザー名とメールアドレスを設定
      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<email-address>"

      # 新しいブランチを作成して切り替え
      - name: Create and switch to new branch
        run: |
          git switch -c $BRANCH_NAME

      # 空のコミットを追加
      - name: Add empty commit
        run: |
          git commit --allow-empty -m "Empty commit for draft PR"
          git push origin $BRANCH_NAME

      # ドラフトのプルリクエストを作成
      - name: Create draft pull request
        id: create_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const branch_name = process.env.BRANCH_NAME;
            const pr_title = "${{ github.event.issue.title }}";
            const pr_body = `This is a draft PR for branch \`${branch_name}\` related to the issue #${{ github.event.issue.number }}.`;
            const prResponse = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: pr_title,
              body: pr_body,
              head: branch_name,
              base: 'main',
              draft: true
            });
            core.setOutput('pr_number', prResponse.data.number.toString());

      # issueにブランチ名とプルリクエストのチェックアウトコマンドをコメントとして追加
      - name: Comment on issue with branch name and PR checkout command
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = ${{ github.event.issue.number }};
            const branch_name = process.env.BRANCH_NAME;
            const pr_number = ${{ steps.create_pr.outputs.pr_number }};
            const message = `
            新しいブランチ \`${branch_name}\` が作成されました。
            Checkout with GitHub CLI:
            \`\`\`bash
            gh pr checkout ${pr_number}
            \`\`\`
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
            });
